#!/usr/bin/env python3
"""
Atlantis travel destinations, anchored on real NPCs.

Earlier this could only offer Oceanus, because the only trustworthy Atlantis
coordinate came from Eve-of-Darkness and computing a zone centre is as likely
to put you inside a hillside as on it.

That is no longer a guess. The zones are populated now, so an arrival point
can be taken from something actually standing in the zone -- and a merchant or
a stable master is standing somewhere a player can stand, which is exactly the
property a teleport destination needs.
"""
import os, pathlib, subprocess, sys

PW = None
for line in open(os.path.expanduser("~/gaheris/.env")):
    if line.startswith("DB_PASSWORD="):
        PW = line.split("=", 1)[1].strip()


def q(sql):
    r = subprocess.run(
        ["docker", "exec", "-e", "MYSQL_PWD=" + PW, "opendaoc-db",
         "mysql", "-uroot", "-N", "-B", "-e", sql],
        capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(r.stderr)
    return [l.split("\t") for l in r.stdout.splitlines()
            if l.strip() and "arning" not in l]


# The Midgard copy of Atlantis is the one the existing Oceanus stop already
# points at, so the whole set stays in one region rather than scattering the
# player between three identical copies of the same place.
ZONES = [
    (73, "Oceanus Hesperos"),
    (74, "Mesothalassa"),
    (75, "Oceanus Boreal"),
    (76, "Oceanus Notos"),
    (77, "Oceanus Anatole"),
    (81, "Stygian Delta"),
    (82, "Land of Atum"),
    (84, "Typhon's Reach"),
    (85, "Ashen Isles"),
    (86, "Green Glades"),
    (87, "Arbor Glen"),
]

# Standalone regions with their own map.
SOLO = [
    (88, "Great Pyramid of Stygia"),
    (90, "City of Aerus"),
]

# An NPC that stands where a person can stand.
#
# Merchants first, and for a reason: a merchant stands in a town, on ground, in
# a spot the game intends people to walk to. Anything else is a guess.
ANCHORS = ("DOL.GS.GameMerchant", "DOL.GS.GameBoatStableMaster",
           "DOL.GS.Blacksmith", "DOL.GS.Enchanter", "DOL.GS.GameStableMaster",
           "DOL.GS.Scholar", "DOL.GS.GameNPC")

# Rows that are scenery rather than someone standing somewhere. A barrier or a
# marker light can sit in mid-air or inside a wall, and arriving there is worse
# than not offering the destination at all.
SCENERY = ("barrier", "chest", "light", "marker", "portal", "door",
           "statue", "crystal", "flame", "brazier", "totem")

NOT_SCENERY = " ".join("AND Name NOT LIKE '%%%s%%'" % w for w in SCENERY)

rows = []

bounds = {int(z[0]): (int(z[1]) * 8192, int(z[2]) * 8192, int(z[3]) * 8192, int(z[4]) * 8192)
          for z in q("SELECT ZoneID, OffsetX, OffsetY, Width, Height FROM opendaoc.zones;")}

for zone, label in ZONES:
    ox, oy, w, h = bounds[zone]
    picked = None

    for cls in ANCHORS:
        # Lowest level, not highest.
        #
        # Ordering the other way picks the biggest thing in the zone as the
        # place you materialise -- which produced "greater criosphinx" and
        # "Guardian of the Talos Crystal" as arrival points. You want to land
        # somewhere quiet and walk to the fight.
        got = q("""SELECT Name, X, Y, Z, Heading, ClassType FROM opendaoc.mob
                   WHERE Region = 73 AND ClassType = '%s'
                     AND X BETWEEN %d AND %d AND Y BETWEEN %d AND %d
                     AND Level > 0 %s
                   ORDER BY Level ASC LIMIT 1;"""
                % (cls, ox, ox + w, oy, oy + h, NOT_SCENERY))
        if got:
            picked = got[0]
            break

    if not picked:
        print("  no anchor found for %s" % label, file=sys.stderr)
        continue

    rows.append((label, 73, int(picked[1]), int(picked[2]), int(picked[3]),
                 int(picked[4]), picked[0], picked[5]))

for region, label in SOLO:
    picked = None
    for cls in ANCHORS:
        got = q("""SELECT Name, X, Y, Z, Heading, ClassType FROM opendaoc.mob
                   WHERE Region = %d AND ClassType = '%s' AND Level > 0 %s
                   ORDER BY Level ASC LIMIT 1;""" % (region, cls, NOT_SCENERY))
        if got:
            picked = got[0]
            break

    if not picked:
        print("  no anchor found for %s" % label, file=sys.stderr)
        continue

    rows.append((label, region, int(picked[1]), int(picked[2]), int(picked[3]),
                 int(picked[4]), picked[0], picked[5]))

print("=== anchors chosen ===", file=sys.stderr)
for r in rows:
    print("  %-26s region %-4d %8d,%8d,%6d  (%s)" %
          (r[0], r[1], r[2], r[3], r[4], r[6][:28]), file=sys.stderr)

out = ["""-- ===========================================================================
--  14-atlantis-travel.sql   (generated by tools/mkatldest.py -- do not hand-edit)
--
--  Atlantis on the Gate Warden's menu.
--
--  Until the zones were populated this could offer only Oceanus, because the
--  one trustworthy Atlantis coordinate came from Eve-of-Darkness and a point
--  computed from zone bounds is as likely to sit inside the terrain as on it.
--
--  It is not a guess any more. Each destination is anchored on an NPC actually
--  standing in that zone -- a merchant or a stable master by preference, since
--  something that stands where a player can stand is exactly what a teleport
--  target needs to be.
--
--  All of these are the Midgard copy of Atlantis (region 73), which is where
--  the existing Oceanus stop already went. There is no sense scattering one
--  realm between three identical copies of the same place.
--
--  Needs 13-atlantis-mobs.sql applied first -- without the mobs there is
--  nothing to anchor on.
--  Safe to re-run.
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

DELETE FROM `teleport` WHERE `Type` = 'gaheris' AND `RegionID` IN (73, 88, 90);
"""]

for label, region, x, y, z, h, who, cls in rows:
    out.append(
        "-- anchored on: %s (%s)\n"
        "INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, "
        "`RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES "
        "(UUID(), 'gaheris', '%s', 0, %d, %d, %d, %d, %d);"
        % (who.replace("--", "-"), cls, label.replace("'", "''"), region, x, y, z, h))

out.append("""
SELECT `TeleportID`, `RegionID`, `X`, `Y`, `Z` FROM `teleport`
 WHERE `Type` = 'gaheris' AND `RegionID` IN (73, 88, 90)
 ORDER BY `TeleportID`;
""")

path = pathlib.Path.home() / "gaheris" / "sql" / "14-atlantis-travel.sql"
path.write_text("\n".join(out) + "\n", encoding="utf-8")
print("\nwrote %s (%d destinations)" % (path, len(rows)), file=sys.stderr)
