#!/usr/bin/env python3
"""
Generates the Atlantis population import.

The zones were always there and always empty: 70 mobs across the whole of
Atlantis against 97,737 in the world as a whole. This brings across the
41,727 placements from db-public, the Dawn of Light community database.

It is only placements. Checked before writing a line of it:

  * 1204 of the 1205 NPC templates those mobs reference are already in the
    database, 12 of 12 factions, and 3247 of 3248 equipment templates -- and
    the shared ids name the same creatures, so nothing is being redefined.
  * None of the 70 mobs already standing in Atlantis appear in this set, so
    nothing is duplicated.

Every row is tagged PackageID='gaheris-atlantis', which makes the whole import
reversible with a single DELETE.

Requires db-public checked out; see the path below.
"""
import json, glob, os, pathlib, sys

BASE = "/mnt/e/AITestProjects/UO/db-public/src/data"
OUT = pathlib.Path.home() / "gaheris" / "sql" / "13-atlantis-mobs.sql"
TAG = "gaheris-atlantis"

ATLANTIS = {30, 45, 47, 70, 71, 72, 73, 88, 90, 130, 145, 147}

if not os.path.isdir(BASE):
    sys.exit("db-public not found at %s" % BASE)

# our mob columns, minus the ones we set ourselves
cols = [c.strip() for c in open("/tmp/ourmob.txt") if c.strip()]

mobs = []
for f in sorted(glob.glob(os.path.join(BASE, "Mob.*.json"))):
    with open(f, encoding="utf-8", errors="replace") as fh:
        for r in json.load(fh):
            if isinstance(r, dict) and int(r.get("Region") or -1) in ATLANTIS:
                mobs.append(r)

print("Atlantis placements: %d" % len(mobs), file=sys.stderr)

usable = [c for c in cols if c in mobs[0] or c in ("Mob_ID", "PackageID")]
print("mapping %d of %d mob columns" % (len(usable), len(cols)), file=sys.stderr)


def lit(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return repr(v)
    s = str(v).replace("\\", "\\\\").replace("'", "''")
    return "'" + s + "'"


with OUT.open("w", encoding="utf-8") as fh:
    fh.write("""-- ===========================================================================
--  13-atlantis-mobs.sql   (generated by tools/mkatlantis.py -- do not hand-edit)
--
--  Atlantis, populated.
--
--  The zones were always in the database and always empty: 70 mobs across the
--  whole of Atlantis against 97,737 in the world as a whole. You could sail to
--  Oceanus and find the geography intact and nothing living in it.
--
--  This is 41,727 placements from db-public, the Dawn of Light community
--  database. Placements only -- checked before any of it was written:
--
--    * 1204 of the 1205 NPC templates these reference were already here, 12 of
--      12 factions, and 3247 of 3248 equipment templates. The shared ids name
--      the same creatures (hammerhead shark, Desmona, Leviathan, Behrooz the
--      Jinni), so nothing is being redefined underneath anything.
--    * None of the 70 mobs already standing in Atlantis appear in this set, so
--      nothing here duplicates them.
--
--  Every row is tagged PackageID='gaheris-atlantis'. To undo the whole thing:
--
--      DELETE FROM `mob` WHERE `PackageID` = 'gaheris-atlantis';
--
--  Read at boot: needs a restart. Safe to re-run.
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';
SET autocommit=0;

DELETE FROM `mob` WHERE `PackageID` = 'gaheris-atlantis';

""")

    names = ", ".join("`%s`" % c for c in usable)
    batch = []
    written = 0

    for m in mobs:
        vals = []
        for c in usable:
            if c == "Mob_ID":
                vals.append("UUID()")
            elif c == "PackageID":
                vals.append("'%s'" % TAG)
            else:
                vals.append(lit(m.get(c)))
        batch.append("(" + ", ".join(vals) + ")")

        if len(batch) >= 500:
            fh.write("INSERT INTO `mob` (%s) VALUES\n%s;\n\n" % (names, ",\n".join(batch)))
            written += len(batch)
            batch = []

    if batch:
        fh.write("INSERT INTO `mob` (%s) VALUES\n%s;\n\n" % (names, ",\n".join(batch)))
        written += len(batch)

    fh.write("""COMMIT;
SET autocommit=1;

-- ---------------------------------------------------------------------------
-- Check
-- ---------------------------------------------------------------------------
SELECT `Region`, COUNT(*) AS mobs FROM `mob`
 WHERE `PackageID` = 'gaheris-atlantis'
 GROUP BY `Region` ORDER BY `Region`;

SELECT COUNT(*) AS total_atlantis FROM `mob`
 WHERE `Region` IN (30,45,47,70,71,72,73,88,90,130,145,147);
""")

print("wrote %s (%.1f MB), %d rows"
      % (OUT, OUT.stat().st_size / 1024 / 1024, written), file=sys.stderr)
