#!/usr/bin/env python3
"""
Abermenai and Wilton, designed.

These two battlegrounds are empty and no source can fill them: db-public has
nothing, CapnBry never surveyed them, and the Uthgard bestiary lists creatures
for Abermenai but no coordinates at all. So they are DESIGNED rather than
restored, and this file says so plainly.

What is real: every creature is one that already exists in this world, with
its own model, size and name. Nothing is invented but the arrangement.
"""
import math, pathlib, random, sys

OUT = pathlib.Path.home() / "gaheris" / "sql" / "17-designed-battlegrounds.sql"
TAG = "gaheris-designed"

random.seed(1066)  # so a re-run produces the same world

# (name, model, size, level, per-camp count, number of camps)
ABERMENAI = [
    ("forest cat",          100,  55, 15, 4, 3),
    ("cliff spiderling",     59,  44, 15, 5, 3),
    ("tomte lookout",       671,  51, 15, 3, 2),
    ("black wolf",          102,  46, 16, 4, 3),
    ("wind sprite",         603,  50, 16, 4, 3),
    ("hobgoblin pincher",   251,  42, 16, 3, 2),
    ("savage lynx",         133,  44, 17, 4, 3),
    ("maddened badger",     572,  40, 17, 4, 2),
    ("goblin crawler",      578,  32, 17, 4, 2),
    ("hill hound",          102,  50, 18, 4, 3),
    ("tomte sentinel",      671,  51, 18, 3, 2),
    ("tomte seer",          671,  55, 18, 2, 2),
    ("young scimitar cat",  695,  47, 18, 3, 2),
    ("large red wolfhound",  56,  80, 19, 3, 2),
]
ABERMENAI_BOSS = ("Jarl Abermenai", 153, 65, 19)

WILTON = [
    ("sprawling arachnid",   59, 120, 35, 4, 3),
    ("frost orm",           454,  90, 35, 3, 3),
    ("scimitar cat",        695,  51, 35, 4, 3),
    ("nordic yeti",         460,  64, 36, 3, 3),
    ("hagbui swordbearer",  921,  52, 36, 4, 3),
    ("werewolf",            395,  56, 37, 3, 2),
    ("grovewood",            98,  50, 38, 3, 3),
    ("pristine statue",     993,  75, 39, 2, 2),
    ("legionnaire",         108,  60, 39, 4, 3),
]
WILTON_BOSS = ("Warlord of Wilton", 108, 70, 39)

ZONES = {
    253: {
        "name": "Abermenai", "band": (15, 19),
        "keeps": [(18362, 18257, 4320), (54053, 24680, 4320), (37301, 52362, 3944)],
        "set": ABERMENAI, "boss": ABERMENAI_BOSS,
    },
    240: {
        "name": "Wilton", "band": (35, 39),
        "keeps": [(554521, 583899, 6952), (533631, 535174, 6728), (580637, 538535, 6736)],
        "set": WILTON, "boss": WILTON_BOSS,
    },
}

KEEP_CLEARANCE = 4000   # nothing camps on a portal keep's doorstep


def centre(keeps):
    return (sum(k[0] for k in keeps) // 3, sum(k[1] for k in keeps) // 3)


def ground(keeps, x, y):
    """Nearest keep's Z. Keeps sit on the ground, so it is the best guess."""
    best, bz = None, keeps[0][2]
    for kx, ky, kz in keeps:
        d = (kx - x) ** 2 + (ky - y) ** 2
        if best is None or d < best:
            best, bz = d, kz
    return bz


def camp_spot(keeps, cx, cy, used):
    """Somewhere inside the triangle of keeps, clear of them and of other camps."""
    for _ in range(400):
        ang = random.uniform(0, 2 * math.pi)
        rad = random.uniform(3000, 17000)
        x = int(cx + rad * math.cos(ang))
        y = int(cy + rad * math.sin(ang))

        if any((x - kx) ** 2 + (y - ky) ** 2 < KEEP_CLEARANCE ** 2
               for kx, ky, _ in keeps):
            continue
        if any((x - ux) ** 2 + (y - uy) ** 2 < 2600 ** 2 for ux, uy in used):
            continue

        used.append((x, y))
        return x, y
    return None


def esc(s):
    return str(s).replace("\\", "\\\\").replace("'", "''")


out = ["""-- ===========================================================================
--  17-designed-battlegrounds.sql
--      (generated by tools/mkdesigned.py -- do not hand-edit)
--
--  Abermenai and Wilton, DESIGNED.
--
--  Every other import in this repository is restored data. This one is not,
--  and it should not be mistaken for it. Both zones are empty and no source
--  can fill them: db-public has nothing for either, CapnBry lists Abermenai
--  but surveyed no mobs in it and does not index Wilton at all, and the
--  Uthgard bestiary gives Abermenai a creature list with no coordinates.
--
--  So the arrangement here is invented. What is NOT invented is the
--  creatures: every one already exists in this world, with its own name,
--  model and size, taken from the level band the zone is for. Nothing new was
--  made up to fill them -- only where things stand.
--
--  Levels come from the server's own battleground table rather than from
--  Uthgard's, which bands Abermenai at 20-32. Ours says 15-19, and a zone
--  populated to somebody else's band would be unplayable in its own.
--
--  Camps are laid out inside the triangle of the three portal keeps, kept
--  4000 units clear of each keep so nobody spawns on the doorstep, and 2600
--  apart from each other so a pull is a pull and not the whole zone. Ground
--  height is taken from the nearest keep, which is the best estimate
--  available for a zone nobody has ever walked.
--
--  The random seed is fixed, so re-running rebuilds the same world.
--
--  Tagged PackageID='gaheris-designed'. To undo:
--      DELETE FROM `mob` WHERE `PackageID` = 'gaheris-designed';
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

DELETE FROM `mob` WHERE `PackageID` = 'gaheris-designed';
"""]

MOB = ("`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, "
       "`Size`, `Level`, `ClassType`, `AggroLevel`, `AggroRange`, `Speed`, "
       "`RespawnInterval`, `Realm`, `PackageID`")

summary = []

for region, spec in sorted(ZONES.items()):
    keeps = spec["keeps"]
    cx, cy = centre(keeps)
    used = []
    vals = []

    for name, model, size, level, per, camps in spec["set"]:
        for _ in range(camps):
            spot = camp_spot(keeps, cx, cy, used)
            if not spot:
                continue
            sx, sy = spot
            for i in range(per):
                a = random.uniform(0, 2 * math.pi)
                r = random.uniform(120, 620)
                x = int(sx + r * math.cos(a))
                y = int(sy + r * math.sin(a))
                lv = max(1, level + random.choice((-1, 0, 0, 1)))
                vals.append(
                    "(UUID(), '%s', '', %d, %d, %d, %d, %d, %d, %d, %d, "
                    "'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, '%s')"
                    % (esc(name), x, y, ground(keeps, x, y), region,
                       random.randint(0, 4095), model, size, lv, TAG))

    # one boss, at the centre of the zone, away from every keep
    bname, bmodel, bsize, blevel = spec["boss"]
    vals.append(
        "(UUID(), '%s', 'Warlord', %d, %d, %d, %d, 0, %d, %d, %d, "
        "'DOL.GS.GameNPC', 95, 500, 190, 900000, 0, '%s')"
        % (esc(bname), cx, cy, ground(keeps, cx, cy), region,
           bmodel, bsize, blevel, TAG))

    out.append("-- ---- %s (region %d), levels %d-%d : %d mobs ----"
               % (spec["name"], region, spec["band"][0], spec["band"][1], len(vals)))

    for i in range(0, len(vals), 200):
        out.append("INSERT INTO `mob` (%s) VALUES\n%s;\n"
                   % (MOB, ",\n".join(vals[i:i + 200])))

    summary.append((spec["name"], region, len(vals)))

# ---- Wilton is not a configured battleground; make it one ----------------
out.append("""
-- ---------------------------------------------------------------------------
-- Wilton was never a configured battleground here
-- ---------------------------------------------------------------------------
-- The battleground table has 15-19, 20-24, 25-29, 30-34 and 45-49, and a hole
-- where 35-39 should be. Wilton was that band on live, so it fills its own gap.

DELETE FROM `battleground` WHERE `RegionID` = 240;
INSERT INTO `battleground` (`Battleground_ID`, `RegionID`, `MinLevel`, `MaxLevel`, `MaxRealmLevel`)
VALUES ('Wilton (Level 35-39)', 240, 35, 39, 30);

-- ---------------------------------------------------------------------------
-- Both on the Gate Warden, with a way home
-- ---------------------------------------------------------------------------

DELETE FROM `teleport` WHERE `Type` = 'gaheris' AND `RegionID` IN (240, 253);
DELETE FROM `mob` WHERE `PackageID` = 'gaheris-designed-warden';
""")

for region, spec in sorted(ZONES.items()):
    kx, ky, kz = spec["keeps"][0]
    out.append(
        "INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, "
        "`RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES "
        "(UUID(), 'gaheris', '%s', 0, %d, %d, %d, %d, 0);"
        % (esc(spec["name"]), region, kx + 300, ky + 300, kz))
    out.append(
        "INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, "
        "`Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) "
        "VALUES (UUID(), 'Gate Warden', 'Gate Warden', %d, %d, %d, %d, 0, 63, 50, 70, "
        "'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-designed-warden');"
        % (kx + 420, ky + 420, kz, region))

out.append("""
-- ---------------------------------------------------------------------------
-- Check
-- ---------------------------------------------------------------------------
SELECT `Region`, COUNT(*) AS mobs, MIN(`Level`) AS lo, MAX(`Level`) AS hi
  FROM `mob` WHERE `PackageID` = 'gaheris-designed'
 GROUP BY `Region`;

SELECT `RegionID`, `MinLevel`, `MaxLevel` FROM `battleground` ORDER BY `MinLevel`;
""")

OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
for name, region, n in summary:
    print("%-12s region %-4d %d mobs" % (name, region, n), file=sys.stderr)
print("wrote %s" % OUT, file=sys.stderr)
