#!/usr/bin/env python3
"""
Generates the Master Level import.

OpenDAoC ships the Master Level implementation -- all 59 spell types these
use have handlers -- and the eight spell lines exist. What was missing was
the 66 rows of data that connect them, which is why turning Atlantis on
advanced a hire into a line with nothing in it.

Source: db-public (the Dawn of Light community database).
"""
import json, pathlib, sys

payload = json.load(open("/tmp/ml-payload.json"))
spells = payload["spells"]
lxs = payload["lxs"]

# Two Sojourner rows -- Reveal Crystalseed and Resistance of the Ancients --
# carry a Type of literally "None" in the source data. There is no handler for
# that and there cannot be one, so SkillBase refuses them at load and logs an
# error on every boot. They would do nothing even if they loaded, so they are
# dropped here rather than left to make noise forever.
DEAD = set()
for _s in spells:
    if (_s.get("Type") or "").strip() in ("", "None"):
        DEAD.add(int(_s["SpellID"]))

if DEAD:
    print("dropping typeless spells: %s" % sorted(DEAD), file=sys.stderr)

spells = [_s for _s in spells if int(_s["SpellID"]) not in DEAD]
lxs = [_r for _r in lxs if int(_r["SpellID"]) not in DEAD]

ours = [l.strip() for l in open("/tmp/ourspell.txt") if l.strip()]
theirs = set(spells[0].keys())

# --------------------------------------------------------------- verify
extra = theirs - set(ours)
absent = set(ours) - theirs

if extra:
    print("FIELDS THEY HAVE THAT WE DO NOT: %s" % sorted(extra), file=sys.stderr)
if absent:
    print("COLUMNS WE HAVE THEY DO NOT: %s" % sorted(absent), file=sys.stderr)

cols = [c for c in ours if c in theirs]
print("mapping %d of our %d spell columns" % (len(cols), len(ours)), file=sys.stderr)


def lit(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return repr(v)
    s = str(v).replace("\\", "\\\\").replace("'", "''")
    return "'" + s + "'"


out = []
out.append("""-- ===========================================================================
--  12-master-levels.sql   (generated by tools/mkml.py -- do not hand-edit)
--
--  The Master Level spells.
--
--  OpenDAoC already implements Atlantis: all fifty-nine spell types these use
--  have handlers in the core, and the eight Master Level spell lines are in
--  the database. What was missing was the sixty-six rows joining the two --
--  which is why gaheris_atlantis could be switched on and grant nothing at
--  all: it advanced a hire into a line that was empty.
--
--  Source: db-public, the Dawn of Light community database.
--
--  Spell ids 7201-7319 are free here; checked against every id in the spell
--  table before this was written.
--
--  Needs nothing in the scripts directory. Read at boot: needs a restart.
--  Safe to re-run.
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

-- ---------------------------------------------------------------------------
-- 1. The spells
-- ---------------------------------------------------------------------------
""")

for s in sorted(spells, key=lambda r: int(r["SpellID"])):
    names = ", ".join("`%s`" % c for c in cols)
    vals = ", ".join(lit(s.get(c)) for c in cols)
    updates = ", ".join("`%s`=VALUES(`%s`)" % (c, c) for c in cols if c != "SpellID")
    out.append("INSERT INTO `spell` (%s) VALUES (%s)\n  ON DUPLICATE KEY UPDATE %s;"
               % (names, vals, updates))

out.append("""
-- ---------------------------------------------------------------------------
-- 1b. Typeless spells, if an earlier run inserted them
-- ---------------------------------------------------------------------------
-- Reveal Crystalseed and Resistance of the Ancients carry a Type of literally
-- "None" upstream. SkillBase cannot register a spell with no handler and logs
-- an error for it on every boot, and they would do nothing if it could, so
-- they are removed rather than left to make noise.

DELETE FROM `spell` WHERE `SpellID` IN (7204, 7278);

-- ---------------------------------------------------------------------------
-- 2. Joining them to their lines
-- ---------------------------------------------------------------------------
-- Cleared first so a re-run cannot double them up: LineXSpell_ID is a UUID, so
-- nothing else would stop a second copy of every row.

DELETE FROM `linexspell` WHERE `LineName` IN
  ('Banelord','Battlemaster','Convoker','Perfecter',
   'Sojourner','Spymaster','Stormlord','Warlord');
""")

for r in sorted(lxs, key=lambda r: (str(r["LineName"]), int(r.get("Level") or 0))):
    out.append(
        "INSERT INTO `linexspell` (`LineXSpell_ID`, `LineName`, `SpellID`, `Level`, `PackageID`) "
        "VALUES (UUID(), %s, %d, %d, 'gaheris');"
        % (lit(r["LineName"]), int(r["SpellID"]), int(r.get("Level") or 1)))

out.append("""
-- ---------------------------------------------------------------------------
-- Check
-- ---------------------------------------------------------------------------
SELECT l.LineName, COUNT(*) AS spells
  FROM `linexspell` l
 WHERE l.LineName IN ('Banelord','Battlemaster','Convoker','Perfecter',
                      'Sojourner','Spymaster','Stormlord','Warlord')
 GROUP BY l.LineName ORDER BY l.LineName;

SELECT COUNT(*) AS ml_spells_loaded FROM `spell` WHERE SpellID BETWEEN 7201 AND 7319;
""")

path = pathlib.Path.home() / "gaheris" / "sql" / "12-master-levels.sql"
path.write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote %s" % path, file=sys.stderr)
print("%d spells, %d line links" % (len(spells), len(lxs)), file=sys.stderr)
