#!/usr/bin/env python3
"""
The portal circles, and travel that goes both ways.

Replaces the Old Frontiers portal ceremony -- a ring of six casters around one
teleporter, at each of the nine border-keep portals -- with a single Gate
Warden serving the whole catalogue. And puts a warden at the far end of every
long trip, so Atlantis and the battlegrounds stop being one-way.
"""
import os, pathlib, subprocess, sys

PW = None
for line in open(os.path.expanduser("~/gaheris/.env")):
    if line.startswith("DB_PASSWORD="):
        PW = line.split("=", 1)[1].strip()


def q(sql):
    r = subprocess.run(
        ["docker", "exec", "-e", "MYSQL_PWD=" + PW, "opendaoc-db",
         "mysql", "-uroot", "-N", "-B", "-e", sql],
        capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(r.stderr)
    return [l.split("\t") for l in r.stdout.splitlines()
            if l.strip() and "arning" not in l]


BATTLEGROUNDS = {
    234: "The Proving Grounds", 235: "The Lion's Den", 236: "The Hills of Claret",
    237: "Killaloe", 238: "Thidranki", 239: "Braemar", 240: "Wilton",
    241: "Molvik", 242: "Leirvik", 244: "Passage of Conflict",
    246: "Dodens Gruva", 248: "Summoner's Hall", 250: "Caledon",
    253: "Abermenai", 165: "Cathal Valley",
}

ANCHORS = ("DOL.GS.GameMerchant", "DOL.GS.GameHealer", "DOL.GS.GameStableMaster",
           "DOL.GS.Blacksmith", "DOL.GS.GameNPC")


def anchor(region):
    """Somewhere in this region a person can stand. Quietest thing available."""
    for cls in ANCHORS:
        got = q("""SELECT Name, X, Y, Z, Heading FROM opendaoc.mob
                   WHERE Region = %d AND ClassType = '%s' AND Level > 0
                     AND Name NOT LIKE '%%barrier%%' AND Name NOT LIKE '%%light%%'
                   ORDER BY Level ASC LIMIT 1;""" % (region, cls))
        if got:
            return got[0]
    return None


def esc(s):
    return str(s).replace("\\", "\\\\").replace("'", "''")


out = ["""-- ===========================================================================
--  16-portals.sql   (generated by tools/mkportals.py -- do not hand-edit)
--
--  One teleporter instead of a ceremony, and travel that goes both ways.
--
--  At each of the nine border-keep portals stood a ring of six casters --
--  DOL.GS.Scripts.OFAssistant, called Master Elementalist in Albion, Seoltoir
--  or Master Enchanter in Hibernia, Gothi of Odin in Midgard -- around a
--  single DOL.GS.Scripts.OFTeleporter in the middle. Fifty-four mages doing a
--  ceremony for a portal that, on a one-realm server, only ever needed to be a
--  door.
--
--  The ring goes. The one in the middle becomes a Gate Warden and serves the
--  whole catalogue: Albion, Midgard, Hibernia, Shrouded Isles, Atlantis, the
--  dungeons and the battlegrounds.
--
--  The far end is the other half of this. A destination you cannot come back
--  from is a trap, and Atlantis had exactly that problem -- so there is now a
--  warden standing at every Atlantis arrival point and in every battleground.
--
--  Safe to re-run.
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

-- ---------------------------------------------------------------------------
-- 1. The ring of mages goes
-- ---------------------------------------------------------------------------

DELETE FROM `mob` WHERE `ClassType` = 'DOL.GS.Scripts.OFAssistant';

-- ---------------------------------------------------------------------------
-- 2. The one in the middle becomes a Gate Warden
-- ---------------------------------------------------------------------------
-- Kept in place, keeping its own name and model -- Master Visur, Glasny and
-- Stor Gothi have stood at those portals for twenty years. Only what happens
-- when you talk to them changes.

UPDATE `mob`
   SET `ClassType` = 'DOL.GS.Scripts.GaherisTeleporter',
       `Guild` = 'Gate Warden'
 WHERE `ClassType` = 'DOL.GS.Scripts.OFTeleporter';

-- ---------------------------------------------------------------------------
-- 3. A way back from the far side
-- ---------------------------------------------------------------------------

DELETE FROM `mob` WHERE `PackageID` = 'gaheris-wardens';
"""]

MOB = ("`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, "
       "`Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`")

placed = 0

# ---- Atlantis: a warden at every arrival point ------------------------
for row in q("""SELECT TeleportID, RegionID, X, Y, Z, Heading FROM opendaoc.teleport
                WHERE Type='gaheris' AND RegionID IN (73,88,90);"""):
    label, region, x, y, z, h = row[0], int(row[1]), int(row[2]), int(row[3]), int(row[4]), int(row[5])
    out.append(
        "INSERT INTO `mob` (%s) VALUES\n"
        "  (UUID(), 'Bound Djinn', 'Gate Warden', %d, %d, %d, %d, %d, 1198, 55, 70, "
        "'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- %s"
        % (MOB, x + 120, y + 120, z, region, h, esc(label)))
    placed += 1

# ---- Battlegrounds: destination AND a warden --------------------------
out.append("""
-- ---------------------------------------------------------------------------
-- 4. The battlegrounds
-- ---------------------------------------------------------------------------
-- Not one of the sixteen was in the catalogue. Each is anchored on the
-- quietest NPC standing in it, on the same rule as the Atlantis stops: a
-- merchant or a healer stands where a person can stand.

DELETE FROM `teleport` WHERE `Type` = 'gaheris' AND `RegionID` IN
  (165,234,235,236,237,238,239,240,241,242,244,246,248,250,253);
""")

found = 0
for region, label in sorted(BATTLEGROUNDS.items()):
    a = anchor(region)
    if not a:
        print("  no anchor in %s (region %d)" % (label, region), file=sys.stderr)
        continue

    who, x, y, z, h = a[0], int(a[1]), int(a[2]), int(a[3]), int(a[4])
    found += 1

    out.append(
        "-- %s, anchored on: %s\n"
        "INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, "
        "`RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES "
        "(UUID(), 'gaheris', '%s', 0, %d, %d, %d, %d, %d);"
        % (esc(label), esc(who), esc(label), region, x, y, z, h))

    out.append(
        "INSERT INTO `mob` (%s) VALUES\n"
        "  (UUID(), 'Gate Warden', 'Gate Warden', %d, %d, %d, %d, %d, 63, 50, 70, "
        "'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');"
        % (MOB, x + 120, y + 120, z, region, h))
    placed += 1

out.append("""
-- ---------------------------------------------------------------------------
-- Check
-- ---------------------------------------------------------------------------
SELECT 'circle mages left', COUNT(*) FROM `mob` WHERE `ClassType`='DOL.GS.Scripts.OFAssistant'
UNION ALL SELECT 'OFTeleporters left', COUNT(*) FROM `mob` WHERE `ClassType`='DOL.GS.Scripts.OFTeleporter'
UNION ALL SELECT 'gate wardens', COUNT(*) FROM `mob` WHERE `ClassType`='DOL.GS.Scripts.GaherisTeleporter'
UNION ALL SELECT 'destinations', COUNT(*) FROM `teleport` WHERE `Type`='gaheris';
""")

path = pathlib.Path.home() / "gaheris" / "sql" / "16-portals.sql"
path.write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote %s" % path, file=sys.stderr)
print("battlegrounds anchored: %d of %d, wardens placed: %d"
      % (found, len(BATTLEGROUNDS), placed), file=sys.stderr)
