#!/usr/bin/env python3
"""
Generates the travel catalogue.

Destinations come from Eve-of-Darkness's Teleport.json -- a working server's
own teleport table, so the coordinates are tested rather than computed -- and
are merged into the teleport table core already reads.
"""
import json, pathlib

src = pathlib.Path.home() / "dol-db" / "Teleport.json"
out = pathlib.Path.home() / "gaheris" / "sql" / "11-travel-catalogue.sql"

rows = json.loads(src.read_text(encoding="utf-8", errors="replace"))

# Types that are plumbing rather than places you would ask to go.
SKIP_IDS = {"entrance", "guild", "hearth", "bind", "house", "market"}

seen = set()
kept = []

for r in rows:
    tid = (r.get("TeleportID") or "").strip()
    region = r.get("RegionID")

    if not tid or region is None:
        continue
    if tid.lower() in SKIP_IDS:
        continue

    # An emissary is a person, not a destination.
    if "emissary" in (r.get("Type") or "").lower():
        continue

    # Placeholders, not places: region 0 with no coordinates is a relative
    # entry core resolves elsewhere, and teleporting to 0,0,0 is a hole.
    if int(region) == 0:
        continue
    if int(r.get("X") or 0) == 0 and int(r.get("Y") or 0) == 0:
        continue

    # Deduplicate on NAME alone, not name-and-region.
    #
    # Core keys a teleporter as "Type:TeleportID", so the same name in two
    # regions is a collision it refuses at load -- and the menu is addressed
    # by name, so the second one could never have been asked for anyway.
    key = tid.lower()
    if key in seen:
        continue
    seen.add(key)

    kept.append({
        "id": tid,
        "region": int(region),
        "x": int(r.get("X") or 0),
        "y": int(r.get("Y") or 0),
        "z": int(r.get("Z") or 0),
        "h": int(r.get("Heading") or 0),
        "realm": int(r.get("Realm") or 0),
    })

kept.sort(key=lambda d: (d["region"], d["id"].lower()))


def esc(s):
    return s.replace("\\", "\\\\").replace("'", "''")


lines = []
lines.append("""-- ===========================================================================
--  11-travel-catalogue.sql   (generated by tools/mktravel.py -- do not hand-edit)
--
--  The travel catalogue: everywhere a Gate Warden will send you.
--
--  Gaheris had one teleporter that reached the whole world, so this replaces
--  the warden-per-keep network with a single full-service stop. The wardens at
--  the keeps are removed here; the ones in the three capitals stay, and now
--  offer everything.
--
--  Destinations are taken from Eve-of-Darkness's own teleport table rather
--  than computed from zone bounds, because those coordinates come off a
--  server people actually played on -- a zone centre is easy to calculate and
--  will happily drop you inside a hillside.
--
--  Needs GaherisTravel.cs in the scripts directory.
--  Safe to re-run.
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

-- ---------------------------------------------------------------------------
-- 1. The destinations
-- ---------------------------------------------------------------------------
""")

lines.append("DELETE FROM `teleport` WHERE `Type` = 'gaheris';\n")

for d in kept:
    lines.append(
        "INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, "
        "`RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES "
        "(UUID(), 'gaheris', '%s', %d, %d, %d, %d, %d, %d);"
        % (esc(d["id"]), d["realm"], d["region"], d["x"], d["y"], d["z"], d["h"])
    )

# --------------------------------------------------------------- Atlantis
lines.append("""
-- ---------------------------------------------------------------------------
-- 2. Atlantis
-- ---------------------------------------------------------------------------
-- Oceanus comes through with the rest of the catalogue above; it is the only
-- Atlantis coordinate that comes off a working server, and it is the hub in
-- any case. Mesothalassa, Stygian Delta, Typhon's Reach and Green Glades are
-- all the same region, so you swim to them -- which is how Atlantis is laid
-- out and does not need a teleport of its own.
--
-- Nothing is invented here on purpose. The remaining Atlantis coordinates
-- would have to be computed from zone bounds, and a computed point in a land
-- zone is as likely to be inside the terrain as on it.
--
-- NOTE: these zones are EMPTY. The upstream world data carries 70 mobs across
-- the whole of Atlantis, against 97,737 in the world as a whole -- so this
-- gets you there to look at it, and nothing more.
""")

# ------------------------------------------------- remove the keep wardens
lines.append("""
-- ---------------------------------------------------------------------------
-- 3. One teleporter, not thirty-three
-- ---------------------------------------------------------------------------
-- The wardens standing at every keep were the destination list: the network
-- could only reach a place that had one. A catalogue does not need them, and
-- thirty of them made the menu a wall of keep names.
--
-- The three capitals keep theirs. Region 1/100/200 are the frontiers.

DELETE FROM `mob`
 WHERE `ClassType` = 'DOL.GS.Scripts.GaherisTeleporter'
   AND `Region` IN (1, 100, 200);

-- ---------------------------------------------------------------------------
-- Check
-- ---------------------------------------------------------------------------
SELECT 'destinations', COUNT(*) FROM `teleport` WHERE `Type` = 'gaheris'
UNION ALL
SELECT 'wardens left', COUNT(*) FROM `mob`
 WHERE `ClassType` = 'DOL.GS.Scripts.GaherisTeleporter';
""")

out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote %s" % out)
print("destinations: %d across %d regions" % (len(kept), len({d["region"] for d in kept})))
