#!/usr/bin/env python3
"""
Deep Volcanus, populated.

The one Atlantis zone db-public cannot fill. Placements come from CapnBry's
radar survey; the models do not exist in any source and are chosen here.
"""
import json, re, pathlib, sys, collections

rows = json.load(open("/tmp/volcanus.json"))
OUT = pathlib.Path.home() / "gaheris" / "sql" / "15-volcanus.sql"
TAG = "gaheris-volcanus"

SCAFFOLD = re.compile(
    r"spell effect|fire explosion|flame sphere|mystical barrier|monster generator|"
    r"Mediator Control|'s Gate|'s Passage|Katorii's (Blood|Breath|Deathtouch|"
    r"Foresight|Gaze|Touch)", re.I)

FACTION = {"apophian": 1199, "hephaestian": 1196, "shaitan": 1198, "volurgon": 1197}

NAMED = {
    "Typhon":              (830, 100), "Katorii":            (1195, 85),
    "shaitan idol":        (1203, 70), "Flame of Volcanus":  (456, 75),
    "Typhon's Essence":    (456, 55),  "Balance of the Four": (1203, 65),
    "Battlewarder":        (666, 60),  "Ancient Transmuter": (1191, 50),
    "Katorii's pet":       (1202, 45),
}


def pick(name):
    if name in NAMED:
        return NAMED[name]
    low = name.lower()
    for fam, model in FACTION.items():
        if fam in low:
            big = any(w in low for w in ("archon", "mediator", "zealot"))
            return model, (65 if big else 50)
    return 1198, 50


keep = [r for r in rows if not SCAFFOLD.search(r["name"])]
print("importing %d placements (%d excluded as scaffolding)"
      % (len(keep), len(rows) - len(keep)), file=sys.stderr)


def esc(s):
    return str(s).replace("\\", "\\\\").replace("'", "''")


out = ["""-- ===========================================================================
--  15-volcanus.sql   (generated by tools/mkvolcanus.py -- do not hand-edit)
--
--  Deep Volcanus, populated.
--
--  The one Atlantis zone db-public cannot fill: it has nothing at all for
--  regions 46, 89 or 146. Placements here come from CapnBry's radar survey of
--  zone 89, which records name, level and position but no model -- and none of
--  these creatures exists anywhere else in the world to borrow one from, so
--  every model below is a judgement rather than data.
--
--  The four factions are elemental genies, and the genie models are already in
--  the world from the Atlantis import, so each faction gets its own and they
--  read as four peoples rather than one mob recoloured:
--
--      apophian     1199  efreeti          (fire)
--      hephaestian  1196  dao              (earth, the forge people)
--      shaitan      1198  jinni
--      volurgon     1197  the fourth djinn model
--
--  Twenty names are deliberately NOT imported. They are the scaffolding of a
--  scripted raid -- spell effect markers, monster generators, a mediator
--  control, gates and barriers, one row per boss ability -- and OpenDAoC has
--  no script for any of it. Without the scripts they are invisible props.
--
--  So this is a populated level 60-85 fire dungeon. It is NOT Master Level 7:
--  the trials are scripted content and none of that scripting exists.
--
--  Every row is tagged PackageID='gaheris-volcanus'. To undo:
--      DELETE FROM `mob` WHERE `PackageID` = 'gaheris-volcanus';
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

DELETE FROM `mob` WHERE `PackageID` = 'gaheris-volcanus';
"""]

vals = []
for r in keep:
    model, size = pick(r["name"])
    lvl = max(1, min(85, int(r["level"] or 1)))
    aggro = 0 if r["name"] in ("Ancient Transmuter", "Battlewarder") else 90
    vals.append(
        "(UUID(), '%s', '', %d, %d, %d, %d, 0, %d, %d, %d, 'DOL.GS.GameNPC', "
        "%d, %d, 200, 0, '%s')"
        % (esc(r["name"]), r["x"], r["y"], r["z"], r["region"], model, size, lvl,
           aggro, 400, TAG))

names = ("`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, "
         "`Model`, `Size`, `Level`, `ClassType`, `AggroLevel`, `AggroRange`, "
         "`Speed`, `Realm`, `PackageID`")

for i in range(0, len(vals), 250):
    out.append("INSERT INTO `mob` (%s) VALUES\n%s;\n"
               % (names, ",\n".join(vals[i:i + 250])))

out.append("""
SELECT `Name`, `Model`, `Level`, COUNT(*) AS placements FROM `mob`
 WHERE `PackageID` = 'gaheris-volcanus'
 GROUP BY `Name`, `Model`, `Level` ORDER BY `Level` DESC LIMIT 12;

SELECT COUNT(*) AS volcanus_total FROM `mob` WHERE `PackageID` = 'gaheris-volcanus';
""")

OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote %s" % OUT, file=sys.stderr)
