#!/usr/bin/env python3
"""
Generates gaheris-travel.sql -- the travel network, and mercenary recruiters
at the three border keeps.

Placing a warden at a keep is a coordinate problem: the keep table gives the
keep's centre, which is inside the walls, and guessing a point "outside" means
guessing a ground height too. Get Z wrong and the warden floats or sinks.

So it does not guess. For each keep it takes the garrison guard standing
furthest from the centre at ground level, and puts the warden on that exact
spot -- a position the server already accepts, on ground a guard is already
standing on, at the outer edge of the garrison. That is also where you want to
arrive: in sight of the keep, outside it, at the start of the approach.

Run against the live database:
    python3 mkwardens.py > gaheris-travel.sql
"""

import subprocess

CONTAINER = "opendaoc-db"
DB = "opendaoc"
PASSWORD = "00rAI17l9AvCGNhUiCfoduUvohuYyca3"

# Every keep converted to evil hands, in menu order within each frontier.
KEEPS = [50, 51, 52, 53, 54, 55, 56, 57, 58,
         75, 76, 77, 78, 79, 80, 81, 82, 198,
         100, 101, 102, 103, 104, 105, 106, 110, 111]

# The three staging points, and the three capitals beside the seal collectors.
# Nothing here is derived, so these stay as written.
FIXED = [
    ("Castle Sauvage", 1,   584151, 477177, 2600, 1198, True),
    ("Svasud Faste",   100, 767242, 669591, 5736, 1198, True),
    ("Druim Ligen",    200, 334342, 419994, 5184, 1198, True),
    ("Camelot",        10,  33575,  22668,  8479, 2100, False),
    ("Jordheim",       101, 31683,  33839,  8030, 2100, False),
    ("Tir na Nog",     201, 32333,  33049,  7998, 2100, False),
]

WARDEN_MODEL = 334
RECRUITER_MODEL = 334
PEACE = 16


def query(sql):
    out = subprocess.run(
        ["wsl", "-d", "Ubuntu", "--", "docker", "exec", CONTAINER,
         "mysql", "-uroot", "-p" + PASSWORD, DB, "-N", "-e", sql],
        capture_output=True, text=True).stdout
    return [line.split("\t") for line in out.strip().splitlines() if line and "\t" in line]


def keep_stops():
    """One stop per keep, on the outermost ground-level guard's own position."""
    stops = []

    for keep_id in KEEPS:
        rows = query(f"""
            SELECT k.Name, k.Region, m.X, m.Y, m.Z, k.Heading
            FROM keep k JOIN mob m ON m.Region = k.Region
              AND m.ClassType LIKE 'DOL.GS.Scripts.Monster%'
              AND ABS(m.Z - k.Z) < 300
              AND SQRT(POW(m.X-k.X,2)+POW(m.Y-k.Y,2)) BETWEEN 800 AND 3000
            WHERE k.KeepID = {keep_id}
            ORDER BY SQRT(POW(m.X-k.X,2)+POW(m.Y-k.Y,2)) DESC
            LIMIT 1;""")

        if rows:
            name, region, x, y, z, heading = rows[0]
            stops.append((name, int(region), int(x), int(y), int(z), int(heading)))
            continue

        # No ground guard in range -- a relic keep, or one whose garrison sits
        # entirely on the walls. Fall back to the keep's own front, which is at
        # least a height the keep itself is defined at.
        rows = query(f"SELECT Name, Region, X, Y, Z, Heading FROM keep WHERE KeepID = {keep_id};")

        if not rows:
            continue

        import math
        name, region, x, y, z, heading = rows[0]
        angle = int(heading) * math.pi / 2048.0
        stops.append((name, int(region),
                      int(int(x) - math.sin(angle) * 1600),
                      int(int(y) + math.cos(angle) * 1600),
                      int(z), int(heading)))
        print(f"-- {name}: no ground guard found, placed 1600 out along the keep heading.")

    return stops


def mob(mob_id, name, guild, class_type, x, y, z, heading, region, model):
    return (
        f"INSERT INTO `mob`\n"
        f" (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,\n"
        f"  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,\n"
        f"  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,\n"
        f"  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)\n"
        f" VALUES\n"
        f" ('{mob_id}','{name}','{guild}','{class_type}',\n"
        f"  {x},{y},{z},{heading},{region},{model},50,70,0,\n"
        f"  {PEACE},0,0,0,'GaherisTravel',\n"
        f"  0,0,0,0,0,0,0,0,0, 0,0,0);\n")


def slug(name):
    return name.lower().replace(" ", "_").replace("'", "")


def main():
    print("-- " + "=" * 73)
    print("--  gaheris-travel.sql   (generated by mkwardens.py -- do not hand-edit)")
    print("--")
    print("--  The travel network: a Gate Warden at every keep, at the three border")
    print("--  keeps and in the three capitals. Every warden reaches every other one.")
    print("--")
    print("--  Also puts a Mercenary Recruiter at each border keep, so a company can")
    print("--  be hired at the staging point rather than only back in the city.")
    print("--")
    print("--  Needs GaherisTravel.cs and Mercenaries.cs in the scripts directory.")
    print("--  Safe to re-run.")
    print("-- " + "=" * 73)
    print()
    print("SET NAMES utf8mb4;")
    print("SET SESSION sql_mode='';")
    print()
    print("DELETE FROM `mob` WHERE `PackageID`='GaherisTravel';")
    print()

    print("-- " + "-" * 73)
    print("-- Wardens at the keeps")
    print("-- " + "-" * 73)
    print("-- Each sits on the outermost ground-level guard's own position: real")
    print("-- ground, outside the walls, at the edge of the garrison.")
    print()

    for name, region, x, y, z, heading in keep_stops():
        print(mob("gaheris_warden_" + slug(name), "Gate Warden", name,
                  "DOL.GS.Scripts.GaherisTeleporter", x, y, z, heading, region, WARDEN_MODEL))

    print("-- " + "-" * 73)
    print("-- Wardens at the border keeps and in the cities")
    print("-- " + "-" * 73)
    print()

    for name, region, x, y, z, heading, is_border in FIXED:
        print(mob("gaheris_warden_" + slug(name), "Gate Warden", name,
                  "DOL.GS.Scripts.GaherisTeleporter", x, y, z, heading, region, WARDEN_MODEL))

    print("-- " + "-" * 73)
    print("-- Recruiters at the border keeps")
    print("-- " + "-" * 73)
    print("-- The city recruiter in Tir na Nog stays where it is; these are for")
    print("-- hiring at the staging point instead of walking a company out.")
    print()

    for name, region, x, y, z, heading, is_border in FIXED:
        if not is_border:
            continue

        print(mob("gaheris_recruiter_" + slug(name), "Mercenary Recruiter", "Free Companies",
                  "DOL.GS.Scripts.MercenaryRecruiter", x + 90, y + 90, z, heading, region,
                  RECRUITER_MODEL))

    print("-- Teardown:")
    print("-- DELETE FROM `mob` WHERE `PackageID`='GaherisTravel';")


if __name__ == "__main__":
    main()
