-- =========================================================================
--  gaheris-travel.sql   (generated by mkwardens.py -- do not hand-edit)
--
--  The travel network: a Gate Warden at every keep, at the three border
--  keeps and in the three capitals. Every warden reaches every other one.
--
--  Also puts a Mercenary Recruiter at each border keep, so a company can
--  be hired at the staging point rather than only back in the city.
--
--  Needs GaherisTravel.cs and Mercenaries.cs in the scripts directory.
--  Safe to re-run.
-- =========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

DELETE FROM `mob` WHERE `PackageID`='GaherisTravel';

-- -------------------------------------------------------------------------
-- Wardens at the keeps
-- -------------------------------------------------------------------------
-- Each sits on the outermost ground-level guard's own position: real
-- ground, outside the walls, at the edge of the garrison.

-- Dun Lamfhota: no ground guard found, placed 1600 out along the keep heading.
INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_caer_benowyc','Gate Warden','Caer Benowyc','DOL.GS.Scripts.GaherisTeleporter',
  651797,346689,6255,4088,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_caer_berkstead','Gate Warden','Caer Berkstead','DOL.GS.Scripts.GaherisTeleporter',
  584079,388967,5846,1118,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_caer_erasleigh','Gate Warden','Caer Erasleigh','DOL.GS.Scripts.GaherisTeleporter',
  620109,369056,6136,943,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_caer_boldiam','Gate Warden','Caer Boldiam','DOL.GS.Scripts.GaherisTeleporter',
  624442,408053,6518,3054,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_caer_sursbrooke','Gate Warden','Caer Sursbrooke','DOL.GS.Scripts.GaherisTeleporter',
  582869,367240,5848,3129,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_caer_hurbury','Gate Warden','Caer Hurbury','DOL.GS.Scripts.GaherisTeleporter',
  548189,337583,4960,2546,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_caer_renaris','Gate Warden','Caer Renaris','DOL.GS.Scripts.GaherisTeleporter',
  580699,431360,4609,3039,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_castle_excalibur','Gate Warden','Castle Excalibur','DOL.GS.Scripts.GaherisTeleporter',
  601376,428650,5664,1920,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_castle_myrddin','Gate Warden','Castle Myrddin','DOL.GS.Scripts.GaherisTeleporter',
  507766,310486,6832,3645,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_bledmeer_faste','Gate Warden','Bledmeer Faste','DOL.GS.Scripts.GaherisTeleporter',
  648419,585685,7344,4094,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_nottmoor_faste','Gate Warden','Nottmoor Faste','DOL.GS.Scripts.GaherisTeleporter',
  676641,629125,5158,4094,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_hlidskialf_faste','Gate Warden','Hlidskialf Faste','DOL.GS.Scripts.GaherisTeleporter',
  679385,653193,5674,2089,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_blendrake_faste','Gate Warden','Blendrake Faste','DOL.GS.Scripts.GaherisTeleporter',
  701275,630448,4382,4051,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_glenlock_faste','Gate Warden','Glenlock Faste','DOL.GS.Scripts.GaherisTeleporter',
  707245,655868,5183,2060,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_fensalir_faste','Gate Warden','Fensalir Faste','DOL.GS.Scripts.GaherisTeleporter',
  738695,655502,7024,1567,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_arvakr_faste','Gate Warden','Arvakr Faste','DOL.GS.Scripts.GaherisTeleporter',
  697260,681593,6865,525,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_grallarhorn_faste','Gate Warden','Grallarhorn Faste','DOL.GS.Scripts.GaherisTeleporter',
  678946,710624,6912,2977,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_mjollner_faste','Gate Warden','Mjollner Faste','DOL.GS.Scripts.GaherisTeleporter',
  770760,628430,6992,470,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_crauchon','Gate Warden','Dun Crauchon','DOL.GS.Scripts.GaherisTeleporter',
  427700,318273,4728,3107,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_crimthain','Gate Warden','Dun Crimthain','DOL.GS.Scripts.GaherisTeleporter',
  435832,368487,4037,1008,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_bolg','Gate Warden','Dun Bolg','DOL.GS.Scripts.GaherisTeleporter',
  403401,368629,4792,4006,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_nged','Gate Warden','Dun nGed','DOL.GS.Scripts.GaherisTeleporter',
  398843,399277,4328,3069,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_da_behnn','Gate Warden','Dun Da Behnn','DOL.GS.Scripts.GaherisTeleporter',
  430787,404039,4940,1070,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_scathaig','Gate Warden','Dun Scathaig','DOL.GS.Scripts.GaherisTeleporter',
  414048,441967,2888,1540,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_ailinne','Gate Warden','Dun Ailinne','DOL.GS.Scripts.GaherisTeleporter',
  369064,394395,4624,2079,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_dagda','Gate Warden','Dun Dagda','DOL.GS.Scripts.GaherisTeleporter',
  402200,464368,2888,2474,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_dun_lamfhota','Gate Warden','Dun Lamfhota','DOL.GS.Scripts.GaherisTeleporter',
  348969,374947,6032,3925,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

-- -------------------------------------------------------------------------
-- Wardens at the border keeps and in the cities
-- -------------------------------------------------------------------------

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_castle_sauvage','Gate Warden','Castle Sauvage','DOL.GS.Scripts.GaherisTeleporter',
  584151,477177,2600,1198,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_svasud_faste','Gate Warden','Svasud Faste','DOL.GS.Scripts.GaherisTeleporter',
  767242,669591,5736,1198,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_druim_ligen','Gate Warden','Druim Ligen','DOL.GS.Scripts.GaherisTeleporter',
  334342,419994,5184,1198,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_camelot','Gate Warden','Camelot','DOL.GS.Scripts.GaherisTeleporter',
  33575,22668,8479,2100,10,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_jordheim','Gate Warden','Jordheim','DOL.GS.Scripts.GaherisTeleporter',
  31683,33839,8030,2100,101,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_warden_tir_na_nog','Gate Warden','Tir na Nog','DOL.GS.Scripts.GaherisTeleporter',
  32333,33049,7998,2100,201,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

-- -------------------------------------------------------------------------
-- Recruiters at the border keeps
-- -------------------------------------------------------------------------
-- The city recruiter in Tir na Nog stays where it is; these are for
-- hiring at the staging point instead of walking a company out.

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_recruiter_castle_sauvage','Mercenary Recruiter','Free Companies','DOL.GS.Scripts.MercenaryRecruiter',
  584241,477267,2600,1198,1,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_recruiter_svasud_faste','Mercenary Recruiter','Free Companies','DOL.GS.Scripts.MercenaryRecruiter',
  767332,669681,5736,1198,100,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

INSERT INTO `mob`
 (`Mob_ID`,`Name`,`Guild`,`ClassType`,`X`,`Y`,`Z`,`Heading`,`Region`,`Model`,`Size`,`Level`,`Realm`,
  `Flags`,`AggroLevel`,`AggroRange`,`RespawnInterval`,`PackageID`,
  `Speed`,`Strength`,`Constitution`,`Dexterity`,`Quickness`,`Intelligence`,`Piety`,`Empathy`,`Charisma`,
  `OwnerID`,`VisibleWeaponSlots`,`HouseNumber`)
 VALUES
 ('gaheris_recruiter_druim_ligen','Mercenary Recruiter','Free Companies','DOL.GS.Scripts.MercenaryRecruiter',
  334432,420084,5184,1198,200,334,50,70,0,
  16,0,0,0,'GaherisTravel',
  0,0,0,0,0,0,0,0,0, 0,0,0);

-- Teardown:
-- DELETE FROM `mob` WHERE `PackageID`='GaherisTravel';
