-- ===========================================================================
--  11-travel-catalogue.sql   (generated by tools/mktravel.py -- do not hand-edit)
--
--  The travel catalogue: everywhere a Gate Warden will send you.
--
--  Gaheris had one teleporter that reached the whole world, so this replaces
--  the warden-per-keep network with a single full-service stop. The wardens at
--  the keeps are removed here; the ones in the three capitals stay, and now
--  offer everything.
--
--  Destinations are taken from Eve-of-Darkness's own teleport table rather
--  than computed from zone bounds, because those coordinates come off a
--  server people actually played on -- a zone centre is easy to calculate and
--  will happily drop you inside a hillside.
--
--  Needs GaherisTravel.cs in the scripts directory.
--  Safe to re-run.
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

-- ---------------------------------------------------------------------------
-- 1. The destinations
-- ---------------------------------------------------------------------------

DELETE FROM `teleport` WHERE `Type` = 'gaheris';

INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Adribard''s Retreat', 1, 1, 472348, 629103, 1724, 2500);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Avalon Marsh', 1, 1, 462144, 633058, 1739, 1769);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Caer Ulfwych', 1, 1, 521253, 616481, 1785, 3607);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Campacorentin Station', 1, 1, 493679, 591770, 1819, 95);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Castle Sauvage', 1, 1, 583668, 486493, 2184, 3217);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Catacombs of Cordova', 1, 1, 386281, 677881, 6661, 266);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Cornwall Station', 1, 1, 408907, 652791, 4944, 1937);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Cotswold Village', 1, 1, 560467, 511652, 2344, 3398);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Darkness Falls', 1, 1, 599451, 536187, 2960, 3076);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Dartmoor', 1, 1, 388710, 699379, 3280, 37);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Keltoi Fogou', 1, 1, 543335, 636336, 1814, 498);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Llyn Barfog', 1, 1, 451995, 400132, 1896, 3039);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Lyonesse', 1, 1, 348239, 667789, 5865, 957);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Prydwen Keep', 1, 1, 574199, 528948, 2863, 4076);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Snowdonia Fortress', 1, 1, 515959, 372539, 8208, 3325);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Stonehenge Barrows', 1, 1, 587011, 585081, 2100, 973);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Sure', 1, 1, 561015, 511367, 2313, 697);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Swanton Keep', 1, 1, 512118, 381746, 7992, 1080);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Tomb', 2, 1, 560798, 511639, 2344, 373);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Tomb of Mithra', 1, 1, 599978, 522172, 2580, 3435);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'personal', 1, 2, 585071, 561548, 3576, 1036);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'AlbThroneExit', 1, 10, 32689, 24326, 8447, 3080);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Camelot', 1, 10, 36085, 31155, 8002, 2994);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Catacombs of Cardova', 1, 23, 31121, 29955, 16239, 3048);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Tepok''s Mine', 1, 24, 32588, 34776, 15179, 2182);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Fintain', 3, 27, 357012, 353642, 5056, 1894);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Hafheim', 2, 27, 226050, 223025, 5056, 2146);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'hillshire', 1, 27, 95644, 101313, 5340, 1024);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Holtham', 1, 27, 94940, 91818, 5024, 1803);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Avalon City', 1, 50, 31138, 47311, 8313, 2026);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Caer Diogel', 1, 51, 403748, 503110, 4680, 1106);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Caer Gothwaite', 1, 51, 535158, 548589, 4800, 463);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Diogel', 1, 51, 403748, 503110, 4680, 1106);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Fort Gwyntell', 1, 51, 426851, 416460, 5712, 1295);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Gothwaite', 1, 51, 535158, 548589, 4805, 463);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Gwyntell', 1, 51, 426851, 416460, 5712, 1295);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Wearyall', 1, 51, 434585, 493128, 3088, 1043);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Wearyall Village', 1, 51, 434585, 493128, 3088, 1043);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Caer Sidi', 1, 60, 31666, 35986, 18639, 4084);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Krondon', 1, 61, 32772, 31379, 15725, 1017);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Inconnu Crypt', 1, 65, 32900, 35568, 16353, 31);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Oceanus', 1, 73, 271184, 539600, 8344, 645);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Shar Labyrinth', 3, 93, 24307, 27567, 17537, 4059);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Accept', 1, 100, 759130, 700085, 6366, 1486);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Audliten', 2, 100, 729152, 760225, 4573, 42);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Fort Atla', 2, 100, 749218, 817547, 4408, 2058);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Fort Veldon', 2, 100, 801046, 678588, 5299, 1036);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Gna Faste', 2, 100, 787729, 903903, 4744, 517);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Gotar', 2, 100, 771152, 836380, 4624, 364);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Huginfell', 2, 100, 712192, 783970, 4672, 3120);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Malmohus', 2, 100, 730233, 971212, 4476, 651);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Mularn', 2, 100, 803612, 726671, 4743, 2659);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Muspelheim', 2, 100, 820138, 680164, 6415, 3014);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Raumarik', 2, 100, 660618, 764955, 4613, 947);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Svasud Faste', 2, 100, 765518, 673661, 5736, 1671);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Vindsaul Faste', 2, 100, 704110, 738883, 5704, 1845);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Jordheim', 1, 101, 31665, 27495, 8800, 3077);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'MidThroneExit', 2, 101, 31752, 27053, 8830, 27);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Spindelhalla', 2, 125, 32151, 31813, 16371, 3067);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Vendo Caverns', 2, 126, 32776, 33062, 16618, 2024);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Varulvhamn', 2, 127, 35267, 30852, 14995, 1043);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Cursed Tomb', 2, 128, 30156, 31233, 16517, 3068);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Nisse''s Lair', 2, 129, 34693, 33173, 16467, 1019);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Trollheim', 2, 150, 28325, 47589, 15999, 3075);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Aegirhamn', 2, 151, 293910, 356255, 3488, 1199);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Bjarken', 2, 151, 289954, 301796, 4160, 2660);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'City of Aegirhamn', 2, 151, 293910, 356255, 3488, 1199);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Hagall', 2, 151, 379380, 384696, 7752, 31);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Knarr', 2, 151, 302623, 433312, 3204, 3065);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Tuscaren Glacier', 2, 160, 34860, 17945, 18826, 1263);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Iarnvidiur''s Lair', 2, 161, 34797, 37123, 17043, 2043);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Agramon', 1, 163, 546877, 480723, 9272, 3471);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Albion Coast', 1, 163, 563401, 505021, 7879, 0);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Albion Town', 1, 163, 677193, 568367, 8088, 3822);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Catterick Hamlet', 1, 163, 677276, 568343, 8088, 184);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Crair Treflan', 1, 163, 373944, 572847, 8040, 719);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Cruachan Gorge', 3, 163, 396557, 618469, 9825, 1941);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Forest Sauvage', 1, 163, 652700, 617189, 9560, 2815);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Godrborg', 1, 163, 597563, 304676, 8088, 1606);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Hibernia Town', 3, 163, 373626, 572884, 8040, 2189);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Hibernian Coast', 3, 163, 483487, 501098, 7879, 0);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Midgard Coast', 2, 163, 537800, 417585, 7893, 0);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Midgard Town', 2, 163, 597650, 304878, 8088, 3151);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Uppland', 2, 163, 651761, 313723, 9432, 1020);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Valley of Bri Leith', 3, 163, 432550, 680367, 9752, 2480);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Yggdra Forest', 2, 163, 715347, 364830, 9432, 284);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Fomor', 3, 180, 33745, 24206, 16073, 550);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Aalid Feie', 3, 181, 313726, 352686, 3592, 747);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Domnann', 3, 181, 423089, 444756, 5959, 2060);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Droighaid', 3, 181, 379081, 420975, 5528, 1159);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Necht', 3, 181, 428182, 320796, 3411, 3104);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Tur Suil', 3, 190, 38037, 27698, 13247, 5);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Galladoria', 3, 191, 32068, 29565, 17042, 57);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Ardagh', 3, 200, 350446, 553634, 5120, 2794);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Connla', 3, 200, 295765, 642599, 4849, 2343);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Cursed Forest', 3, 200, 446983, 525356, 6448, 3076);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Druim Cain', 3, 200, 421156, 486429, 1824, 2407);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Druim Ligen', 3, 200, 334435, 419941, 5184, 184);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Howth', 3, 200, 343184, 592636, 5456, 1339);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Innis Carthaig', 3, 200, 334622, 720123, 4296, 1712);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Mag Mell', 3, 200, 347811, 490351, 5210, 50);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Shannon Estuary', 3, 200, 309968, 645164, 4848, 1137);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Sheeroe Hills', 3, 200, 358460, 710997, 4912, 2000);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Tir na mBeo', 3, 200, 345698, 528897, 5448, 905);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'HibThroneExit', 1, 201, 33176, 32914, 8008, 2048);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Tir na Nog', 3, 201, 33198, 31407, 8000, 2068);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Coruscating Mine', 3, 220, 33502, 33658, 16046, 1027);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Muire Tomb', 3, 221, 31055, 29865, 16239, 4055);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Spraggon Den', 3, 222, 32722, 34761, 15179, 1933);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Koalinth Caverns', 3, 223, 27336, 32266, 17266, 3064);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Treibh Caillte', 3, 224, 35267, 30879, 14999, 1065);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Kobold Undercity', 2, 243, 31320, 28930, 16398, 1741);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'MidThroneRoom', 2, 360, 32331, 30410, 15563, 3);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'AlbThroneRoom', 2, 394, 32328, 31795, 15901, 17);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'HibThroneRoom', 2, 395, 32329, 31779, 15715, 12);

-- ---------------------------------------------------------------------------
-- 2. Atlantis
-- ---------------------------------------------------------------------------
-- Oceanus is the hub: every other Atlantis zone in the region -- Mesothalassa,
-- Stygian Delta, Typhon's Reach, Green Glades -- is reachable from it without
-- a zone line, which is how Atlantis is laid out in the first place.
--
-- Only Oceanus is listed, and deliberately. It is the one Atlantis coordinate
-- that comes from a working server; the rest would have to be computed from
-- zone bounds, and a computed point in a land zone is as likely to be inside
-- the terrain as on it. Swimming out of Oceanus costs a minute and always
-- works.
--
-- NOTE: these zones are EMPTY. The upstream world data carries 70 mobs across
-- the whole of Atlantis, against 97,737 in the world as a whole -- so this
-- gets you there to look at it, and nothing more.

INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Atlantis', 1, 30, 271184, 539600, 8344, 0);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Atlantis', 2, 73, 271184, 539600, 8344, 0);
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Atlantis', 3, 130, 271184, 539600, 8344, 0);

-- ---------------------------------------------------------------------------
-- 3. One teleporter, not thirty-three
-- ---------------------------------------------------------------------------
-- The wardens standing at every keep were the destination list: the network
-- could only reach a place that had one. A catalogue does not need them, and
-- thirty of them made the menu a wall of keep names.
--
-- The three capitals keep theirs. Region 1/100/200 are the frontiers.

DELETE FROM `mob`
 WHERE `ClassType` = 'DOL.GS.Scripts.GaherisTeleporter'
   AND `Region` IN (1, 100, 200);

-- ---------------------------------------------------------------------------
-- Check
-- ---------------------------------------------------------------------------
SELECT 'destinations', COUNT(*) FROM `teleport` WHERE `Type` = 'gaheris'
UNION ALL
SELECT 'wardens left', COUNT(*) FROM `mob`
 WHERE `ClassType` = 'DOL.GS.Scripts.GaherisTeleporter';

