-- ===========================================================================
--  14-atlantis-travel.sql   (generated by tools/mkatldest.py -- do not hand-edit)
--
--  Atlantis on the Gate Warden's menu.
--
--  Until the zones were populated this could offer only Oceanus, because the
--  one trustworthy Atlantis coordinate came from Eve-of-Darkness and a point
--  computed from zone bounds is as likely to sit inside the terrain as on it.
--
--  It is not a guess any more. Each destination is anchored on an NPC actually
--  standing in that zone -- a merchant or a stable master by preference, since
--  something that stands where a player can stand is exactly what a teleport
--  target needs to be.
--
--  All of these are the Midgard copy of Atlantis (region 73), which is where
--  the existing Oceanus stop already went. There is no sense scattering one
--  realm between three identical copies of the same place.
--
--  Needs 13-atlantis-mobs.sql applied first -- without the mobs there is
--  nothing to anchor on.
--  Safe to re-run.
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

DELETE FROM `teleport` WHERE `Type` = 'gaheris' AND `RegionID` IN (73, 88, 90);

-- anchored on: Amabelle (DOL.GS.GameMerchant)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Oceanus Hesperos', 0, 73, 275662, 541240, 8344, 3299);
-- anchored on: odisse harpy (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Mesothalassa', 0, 73, 334798, 579194, 8294, 3982);
-- anchored on: common stingray (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Oceanus Boreal', 0, 73, 388732, 504232, 3446, 2184);
-- anchored on: Teyrn (DOL.GS.GameMerchant)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Oceanus Notos', 0, 73, 381422, 650897, 8134, 2662);
-- anchored on: Ryma (DOL.GS.GameMerchant)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Oceanus Anatole', 0, 73, 447018, 550186, 8568, 1331);
-- anchored on: Rorsc (DOL.GS.GameMerchant)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Stygian Delta', 0, 73, 330506, 451994, 8112, 2529);
-- anchored on: miw-shersekhmet (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Land of Atum', 0, 73, 244976, 451767, 7875, 267);
-- anchored on: sa (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Typhon''s Reach', 0, 73, 498678, 570834, 11104, 3072);
-- anchored on: bruiser (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Ashen Isles', 0, 73, 551238, 539933, 10616, 1778);
-- anchored on: centaur's friend (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Green Glades', 0, 73, 380268, 663010, 8735, 1908);
-- anchored on: Trainee (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Arbor Glen', 0, 73, 441643, 712546, 13515, 2582);
-- anchored on: corrupt androsphinx (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Great Pyramid of Stygia', 0, 88, 32563, 34536, 15870, 1809);
-- anchored on: muryan (DOL.GS.GameNPC)
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'City of Aerus', 0, 90, 34581, 33003, 19051, 21);

SELECT `TeleportID`, `RegionID`, `X`, `Y`, `Z` FROM `teleport`
 WHERE `Type` = 'gaheris' AND `RegionID` IN (73, 88, 90)
 ORDER BY `TeleportID`;

