-- ===========================================================================
--  16-portals.sql   (generated by tools/mkportals.py -- do not hand-edit)
--
--  One teleporter instead of a ceremony, and travel that goes both ways.
--
--  At each of the nine border-keep portals stood a ring of six casters --
--  DOL.GS.Scripts.OFAssistant, called Master Elementalist in Albion, Seoltoir
--  or Master Enchanter in Hibernia, Gothi of Odin in Midgard -- around a
--  single DOL.GS.Scripts.OFTeleporter in the middle. Fifty-four mages doing a
--  ceremony for a portal that, on a one-realm server, only ever needed to be a
--  door.
--
--  The ring goes. The one in the middle becomes a Gate Warden and serves the
--  whole catalogue: Albion, Midgard, Hibernia, Shrouded Isles, Atlantis, the
--  dungeons and the battlegrounds.
--
--  The far end is the other half of this. A destination you cannot come back
--  from is a trap, and Atlantis had exactly that problem -- so there is now a
--  warden standing at every Atlantis arrival point and in every battleground.
--
--  Safe to re-run.
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

-- ---------------------------------------------------------------------------
-- 1. The ring of mages goes
-- ---------------------------------------------------------------------------

DELETE FROM `mob` WHERE `ClassType` = 'DOL.GS.Scripts.OFAssistant';

-- ---------------------------------------------------------------------------
-- 2. The one in the middle becomes a Gate Warden
-- ---------------------------------------------------------------------------
-- Kept in place, keeping its own name and model -- Master Visur, Glasny and
-- Stor Gothi have stood at those portals for twenty years. Only what happens
-- when you talk to them changes.

UPDATE `mob`
   SET `ClassType` = 'DOL.GS.Scripts.GaherisTeleporter',
       `Guild` = 'Gate Warden'
 WHERE `ClassType` = 'DOL.GS.Scripts.OFTeleporter';

-- ---------------------------------------------------------------------------
-- 3. A way back from the far side
-- ---------------------------------------------------------------------------

DELETE FROM `mob` WHERE `PackageID` = 'gaheris-wardens';

INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 275782, 541360, 8344, 73, 3299, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Oceanus Hesperos
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 334918, 579314, 8294, 73, 3982, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Mesothalassa
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 388852, 504352, 3446, 73, 2184, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Oceanus Boreal
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 381542, 651017, 8134, 73, 2662, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Oceanus Notos
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 447138, 550306, 8568, 73, 1331, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Oceanus Anatole
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 330626, 452114, 8112, 73, 2529, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Stygian Delta
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 245096, 451887, 7875, 73, 267, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Land of Atum
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 498798, 570954, 11104, 73, 3072, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Typhon''s Reach
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 551358, 540053, 10616, 73, 1778, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Ashen Isles
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 380388, 663130, 8735, 73, 1908, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Green Glades
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 441763, 712666, 13515, 73, 2582, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Arbor Glen
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 32683, 34656, 15870, 88, 1809, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- Great Pyramid of Stygia
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Bound Djinn', 'Gate Warden', 34701, 33123, 19051, 90, 21, 1198, 55, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');  -- City of Aerus

-- ---------------------------------------------------------------------------
-- 4. The battlegrounds
-- ---------------------------------------------------------------------------
-- Not one of the sixteen was in the catalogue. Each is anchored on the
-- quietest NPC standing in it, on the same rule as the Atlantis stops: a
-- merchant or a healer stands where a person can stand.

DELETE FROM `teleport` WHERE `Type` = 'gaheris' AND `RegionID` IN
  (165,234,235,236,237,238,239,240,241,242,244,246,248,250,253);

-- Cathal Valley, anchored on: Allia Fletcher
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Cathal Valley', 0, 165, 583546, 584382, 4896, 2814);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 583666, 584502, 4896, 165, 2814, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- The Proving Grounds, anchored on: dim fade
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'The Proving Grounds', 0, 234, 563603, 555007, 7700, 2317);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 563723, 555127, 7700, 234, 2317, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- The Lion''s Den, anchored on: forest giant youth
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'The Lion''s Den', 0, 235, 584322, 556465, 5228, 611);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 584442, 556585, 5228, 235, 611, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- The Hills of Claret, anchored on: scrag
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'The Hills of Claret', 0, 236, 546787, 563980, 8078, 2404);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 546907, 564100, 8078, 236, 2404, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Killaloe, anchored on: boogey spawn
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Killaloe', 0, 237, 536025, 566456, 7920, 2909);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 536145, 566576, 7920, 237, 2909, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Thidranki, anchored on: Siegemaster Salendar
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Thidranki', 0, 238, 562576, 573860, 5408, 3026);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 562696, 573980, 5408, 238, 3026, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Braemar, anchored on: chasm worm larva
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Braemar', 0, 239, 559870, 581177, 5723, 2362);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 559990, 581297, 5723, 239, 2362, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Molvik, anchored on: Siegemaster Wyllam
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Molvik', 0, 241, 532529, 542397, 5992, 1353);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 532649, 542517, 5992, 241, 1353, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Leirvik, anchored on: Perry
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Leirvik', 0, 242, 278231, 273381, 10375, 386);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 278351, 273501, 10375, 242, 386, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Passage of Conflict, anchored on: Rheton
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Passage of Conflict', 0, 244, 29188, 24486, 15487, 537);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 29308, 24606, 15487, 244, 537, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Dodens Gruva, anchored on: innocent
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Dodens Gruva', 0, 246, 31237, 33590, 15853, 1561);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 31357, 33710, 15853, 246, 1561, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Summoner''s Hall, anchored on: disemboweled undead
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Summoner''s Hall', 0, 248, 39655, 28064, 16542, 1065);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 39775, 28184, 16542, 248, 1065, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');
-- Caledon, anchored on: JumpCaledonia
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Caledon', 0, 250, 35300, 59435, 7789, 2466);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES
  (UUID(), 'Gate Warden', 'Gate Warden', 35420, 59555, 7789, 250, 2466, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-wardens');

-- ---------------------------------------------------------------------------
-- Check
-- ---------------------------------------------------------------------------
SELECT 'circle mages left', COUNT(*) FROM `mob` WHERE `ClassType`='DOL.GS.Scripts.OFAssistant'
UNION ALL SELECT 'OFTeleporters left', COUNT(*) FROM `mob` WHERE `ClassType`='DOL.GS.Scripts.OFTeleporter'
UNION ALL SELECT 'gate wardens', COUNT(*) FROM `mob` WHERE `ClassType`='DOL.GS.Scripts.GaherisTeleporter'
UNION ALL SELECT 'destinations', COUNT(*) FROM `teleport` WHERE `Type`='gaheris';

