-- ===========================================================================
--  17-designed-battlegrounds.sql
--      (generated by tools/mkdesigned.py -- do not hand-edit)
--
--  Abermenai and Wilton, DESIGNED.
--
--  Every other import in this repository is restored data. This one is not,
--  and it should not be mistaken for it. Both zones are empty and no source
--  can fill them: db-public has nothing for either, CapnBry lists Abermenai
--  but surveyed no mobs in it and does not index Wilton at all, and the
--  Uthgard bestiary gives Abermenai a creature list with no coordinates.
--
--  So the arrangement here is invented. What is NOT invented is the
--  creatures: every one already exists in this world, with its own name,
--  model and size, taken from the level band the zone is for. Nothing new was
--  made up to fill them -- only where things stand.
--
--  Levels come from the server's own battleground table rather than from
--  Uthgard's, which bands Abermenai at 20-32. Ours says 15-19, and a zone
--  populated to somebody else's band would be unplayable in its own.
--
--  Camps are laid out inside the triangle of the three portal keeps, kept
--  4000 units clear of each keep so nobody spawns on the doorstep, and 2600
--  apart from each other so a pull is a pull and not the whole zone. Ground
--  height is taken from the nearest keep, which is the best estimate
--  available for a zone nobody has ever walked.
--
--  The random seed is fixed, so re-running rebuilds the same world.
--
--  Tagged PackageID='gaheris-designed'. To undo:
--      DELETE FROM `mob` WHERE `PackageID` = 'gaheris-designed';
-- ===========================================================================

SET NAMES utf8mb4;
SET SESSION sql_mode='';

DELETE FROM `mob` WHERE `PackageID` = 'gaheris-designed';

-- ---- Wilton (region 240), levels 35-39 : 86 mobs ----
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `AggroLevel`, `AggroRange`, `Speed`, `RespawnInterval`, `Realm`, `PackageID`) VALUES
(UUID(), 'sprawling arachnid', '', 563876, 545920, 6736, 240, 1207, 59, 120, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 564608, 545979, 6736, 240, 2360, 59, 120, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 563857, 545813, 6736, 240, 477, 59, 120, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 564171, 545357, 6736, 240, 343, 59, 120, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 550642, 558773, 6952, 240, 4048, 59, 120, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 551445, 558212, 6952, 240, 2657, 59, 120, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 551199, 558855, 6952, 240, 978, 59, 120, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 550942, 558924, 6952, 240, 996, 59, 120, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 562810, 564028, 6952, 240, 1302, 59, 120, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 562602, 564492, 6952, 240, 3254, 59, 120, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 562747, 563916, 6952, 240, 2872, 59, 120, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'sprawling arachnid', '', 562963, 563703, 6952, 240, 3329, 59, 120, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 554170, 562412, 6952, 240, 3138, 454, 90, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 554276, 562377, 6952, 240, 1073, 454, 90, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 553962, 561813, 6952, 240, 3512, 454, 90, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 560750, 562439, 6952, 240, 228, 454, 90, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 560229, 562781, 6952, 240, 3140, 454, 90, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 560878, 561905, 6952, 240, 3742, 454, 90, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 558464, 547928, 6736, 240, 2398, 454, 90, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 558655, 547568, 6736, 240, 180, 454, 90, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'frost orm', '', 558573, 547641, 6736, 240, 3756, 454, 90, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 552612, 553399, 6728, 240, 468, 695, 51, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 553131, 553604, 6728, 240, 3693, 695, 51, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 553202, 553140, 6728, 240, 1271, 695, 51, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 553362, 553493, 6728, 240, 1364, 695, 51, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 566582, 553589, 6736, 240, 2128, 695, 51, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 566625, 553359, 6736, 240, 117, 695, 51, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 566457, 553270, 6736, 240, 2924, 695, 51, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 566818, 553883, 6736, 240, 1881, 695, 51, 34, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 558907, 536384, 6736, 240, 3682, 695, 51, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 558875, 536451, 6736, 240, 2695, 695, 51, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 559260, 536553, 6736, 240, 3358, 695, 51, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'scimitar cat', '', 559022, 536465, 6736, 240, 1269, 695, 51, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 562106, 549734, 6736, 240, 2318, 460, 64, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 561262, 549444, 6736, 240, 3087, 460, 64, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 561622, 549356, 6736, 240, 1149, 460, 64, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 563980, 557337, 6736, 240, 1900, 460, 64, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 564138, 558001, 6736, 240, 2248, 460, 64, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 564029, 557769, 6736, 240, 2778, 460, 64, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 556742, 564315, 6952, 240, 2093, 460, 64, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 556648, 564266, 6952, 240, 3831, 460, 64, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'nordic yeti', '', 556497, 563399, 6952, 240, 1550, 460, 64, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 543285, 547650, 6728, 240, 1016, 921, 52, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 543240, 548423, 6728, 240, 3507, 921, 52, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 543440, 547854, 6728, 240, 886, 921, 52, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 543388, 548437, 6728, 240, 151, 921, 52, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 560460, 554431, 6736, 240, 2595, 921, 52, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 560152, 553991, 6736, 240, 2314, 921, 52, 37, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 560577, 554002, 6736, 240, 3891, 921, 52, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 560502, 554319, 6736, 240, 1361, 921, 52, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 546162, 547337, 6728, 240, 1432, 921, 52, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 546564, 548076, 6728, 240, 3161, 921, 52, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 546157, 547626, 6728, 240, 2555, 921, 52, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hagbui swordbearer', '', 545883, 547766, 6728, 240, 2584, 921, 52, 35, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'werewolf', '', 544201, 558560, 6728, 240, 123, 395, 56, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'werewolf', '', 543497, 558424, 6728, 240, 2628, 395, 56, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'werewolf', '', 543693, 558261, 6728, 240, 2908, 395, 56, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'werewolf', '', 551133, 539397, 6728, 240, 2658, 395, 56, 36, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'werewolf', '', 551512, 540068, 6728, 240, 3383, 395, 56, 37, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'werewolf', '', 551389, 539112, 6728, 240, 1567, 395, 56, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 543589, 556121, 6728, 240, 2626, 98, 50, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 543115, 556113, 6728, 240, 73, 98, 50, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 543939, 555968, 6728, 240, 2583, 98, 50, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 550721, 549248, 6728, 240, 2135, 98, 50, 37, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 550435, 549169, 6728, 240, 4030, 98, 50, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 550261, 549781, 6728, 240, 2741, 98, 50, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 554225, 548246, 6728, 240, 2319, 98, 50, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 553394, 548242, 6728, 240, 3922, 98, 50, 37, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'grovewood', '', 553446, 548723, 6728, 240, 3848, 98, 50, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'pristine statue', '', 554372, 564642, 6952, 240, 3380, 993, 75, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'pristine statue', '', 554133, 564981, 6952, 240, 1073, 993, 75, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'pristine statue', '', 551678, 536492, 6728, 240, 2121, 993, 75, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'pristine statue', '', 552376, 535961, 6728, 240, 3718, 993, 75, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 565901, 565341, 6952, 240, 3344, 108, 60, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 566665, 565428, 6952, 240, 3521, 108, 60, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 566521, 565156, 6952, 240, 3411, 108, 60, 40, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 566007, 565644, 6952, 240, 1028, 108, 60, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 549656, 545222, 6728, 240, 2071, 108, 60, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 549224, 545290, 6728, 240, 106, 108, 60, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 549476, 544925, 6728, 240, 3156, 108, 60, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 549774, 544985, 6728, 240, 462, 108, 60, 40, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 570259, 547518, 6736, 240, 791, 108, 60, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 570092, 547044, 6736, 240, 340, 108, 60, 38, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 569538, 546990, 6736, 240, 930, 108, 60, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'legionnaire', '', 569945, 546648, 6736, 240, 1862, 108, 60, 39, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'Warlord of Wilton', 'Warlord', 556263, 552536, 6736, 240, 0, 108, 70, 39, 'DOL.GS.GameNPC', 95, 500, 190, 900000, 0, 'gaheris-designed');

-- ---- Abermenai (region 253), levels 15-19 : 126 mobs ----
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `AggroLevel`, `AggroRange`, `Speed`, `RespawnInterval`, `Realm`, `PackageID`) VALUES
(UUID(), 'forest cat', '', 28180, 41394, 3944, 253, 3776, 100, 55, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 27921, 41020, 3944, 253, 3810, 100, 55, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 27662, 41036, 3944, 253, 1426, 100, 55, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 27579, 41213, 3944, 253, 3472, 100, 55, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 23346, 41340, 3944, 253, 1865, 100, 55, 14, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 23944, 41023, 3944, 253, 3725, 100, 55, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 24372, 41011, 3944, 253, 116, 100, 55, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 23734, 41105, 3944, 253, 947, 100, 55, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 31456, 29439, 4320, 253, 4036, 100, 55, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 30871, 29456, 4320, 253, 605, 100, 55, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 31294, 29328, 4320, 253, 1508, 100, 55, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'forest cat', '', 31612, 29539, 4320, 253, 1703, 100, 55, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 27201, 31615, 4320, 253, 2192, 59, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 27965, 31953, 4320, 253, 2060, 59, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 28108, 32165, 4320, 253, 3818, 59, 44, 14, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 27759, 31812, 4320, 253, 2262, 59, 44, 14, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 27450, 32218, 4320, 253, 2121, 59, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 29928, 17654, 4320, 253, 3544, 59, 44, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 29598, 18161, 4320, 253, 299, 59, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 29688, 18227, 4320, 253, 1778, 59, 44, 14, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 29195, 17868, 4320, 253, 1945, 59, 44, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 29017, 18035, 4320, 253, 3684, 59, 44, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 47832, 28219, 4320, 253, 4088, 59, 44, 14, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 47466, 27849, 4320, 253, 2693, 59, 44, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 47975, 28461, 4320, 253, 580, 59, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 47597, 28354, 4320, 253, 1958, 59, 44, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'cliff spiderling', '', 47403, 27767, 4320, 253, 1215, 59, 44, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte lookout', '', 26821, 26587, 4320, 253, 3204, 671, 51, 14, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte lookout', '', 26878, 26579, 4320, 253, 592, 671, 51, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte lookout', '', 26965, 25953, 4320, 253, 3909, 671, 51, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte lookout', '', 40955, 33786, 4320, 253, 1931, 671, 51, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte lookout', '', 40849, 34528, 4320, 253, 2429, 671, 51, 14, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte lookout', '', 41259, 34521, 4320, 253, 747, 671, 51, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 32201, 35104, 3944, 253, 826, 102, 46, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 32920, 34799, 3944, 253, 2005, 102, 46, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 32187, 34347, 3944, 253, 1703, 102, 46, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 32834, 34805, 3944, 253, 1837, 102, 46, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 24398, 35828, 4320, 253, 2807, 102, 46, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 24354, 35938, 4320, 253, 1254, 102, 46, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 24473, 35932, 4320, 253, 3407, 102, 46, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 24899, 36023, 4320, 253, 1556, 102, 46, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 20141, 36139, 4320, 253, 3164, 102, 46, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 19975, 35665, 4320, 253, 2858, 102, 46, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 20130, 35319, 4320, 253, 3184, 102, 46, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'black wolf', '', 19903, 35461, 4320, 253, 2883, 102, 46, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 34727, 36492, 3944, 253, 1474, 603, 50, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 34086, 36448, 3944, 253, 4051, 603, 50, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 34281, 36212, 3944, 253, 2230, 603, 50, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 34816, 36438, 3944, 253, 3627, 603, 50, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 37230, 20354, 4320, 253, 3127, 603, 50, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 36813, 20833, 4320, 253, 1355, 603, 50, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 36832, 20225, 4320, 253, 743, 603, 50, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 36814, 20276, 4320, 253, 367, 603, 50, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 42844, 23395, 4320, 253, 3329, 603, 50, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 43321, 23006, 4320, 253, 3748, 603, 50, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 42747, 22473, 4320, 253, 96, 603, 50, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'wind sprite', '', 43002, 22645, 4320, 253, 3514, 603, 50, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hobgoblin pincher', '', 42199, 17015, 4320, 253, 3003, 251, 42, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hobgoblin pincher', '', 41785, 17165, 4320, 253, 2194, 251, 42, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hobgoblin pincher', '', 41775, 16707, 4320, 253, 738, 251, 42, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hobgoblin pincher', '', 31899, 23219, 4320, 253, 3231, 251, 42, 15, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hobgoblin pincher', '', 32020, 23311, 4320, 253, 4003, 251, 42, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hobgoblin pincher', '', 31885, 23187, 4320, 253, 3319, 251, 42, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 51164, 31047, 4320, 253, 1337, 133, 44, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 50746, 31231, 4320, 253, 218, 133, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 50966, 31241, 4320, 253, 3877, 133, 44, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 50264, 30839, 4320, 253, 2885, 133, 44, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 34838, 25111, 4320, 253, 3255, 133, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 34412, 25180, 4320, 253, 2666, 133, 44, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 34539, 25360, 4320, 253, 1762, 133, 44, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 34159, 25302, 4320, 253, 3780, 133, 44, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 40375, 40833, 3944, 253, 2645, 133, 44, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 40163, 41183, 3944, 253, 622, 133, 44, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 40207, 41380, 3944, 253, 3897, 133, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'savage lynx', '', 40192, 41074, 3944, 253, 3770, 133, 44, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'maddened badger', '', 29901, 25521, 4320, 253, 125, 572, 40, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'maddened badger', '', 29897, 25567, 4320, 253, 1374, 572, 40, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'maddened badger', '', 29593, 25198, 4320, 253, 740, 572, 40, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'maddened badger', '', 29441, 25720, 4320, 253, 2017, 572, 40, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'maddened badger', '', 32606, 32141, 4320, 253, 2064, 572, 40, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'maddened badger', '', 32048, 32066, 4320, 253, 3146, 572, 40, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'maddened badger', '', 32780, 31974, 4320, 253, 1380, 572, 40, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'maddened badger', '', 32193, 32512, 4320, 253, 1190, 572, 40, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'goblin crawler', '', 46568, 32022, 4320, 253, 1460, 578, 32, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'goblin crawler', '', 46853, 31829, 4320, 253, 643, 578, 32, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'goblin crawler', '', 47440, 31431, 4320, 253, 2722, 578, 32, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'goblin crawler', '', 46772, 31186, 4320, 253, 3642, 578, 32, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'goblin crawler', '', 21516, 27240, 4320, 253, 2585, 578, 32, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'goblin crawler', '', 21696, 26452, 4320, 253, 2878, 578, 32, 16, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'goblin crawler', '', 21861, 27144, 4320, 253, 2467, 578, 32, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'goblin crawler', '', 22011, 27136, 4320, 253, 3038, 578, 32, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 38245, 28444, 4320, 253, 3811, 102, 50, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 37648, 29045, 4320, 253, 1955, 102, 50, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 38222, 29091, 4320, 253, 560, 102, 50, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 37785, 28655, 4320, 253, 1072, 102, 50, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 34881, 28888, 4320, 253, 2081, 102, 50, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 34869, 29041, 4320, 253, 217, 102, 50, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 35102, 29196, 4320, 253, 683, 102, 50, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 34900, 28667, 4320, 253, 3723, 102, 50, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 45777, 39977, 3944, 253, 3257, 102, 50, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 45090, 39433, 3944, 253, 1143, 102, 50, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 45373, 39999, 3944, 253, 2182, 102, 50, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'hill hound', '', 45071, 40249, 3944, 253, 716, 102, 50, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte sentinel', '', 29836, 34947, 3944, 253, 427, 671, 51, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte sentinel', '', 29468, 34735, 3944, 253, 573, 671, 51, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte sentinel', '', 29803, 34925, 3944, 253, 3036, 671, 51, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte sentinel', '', 24153, 21179, 4320, 253, 517, 671, 51, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte sentinel', '', 23687, 20890, 4320, 253, 259, 671, 51, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte sentinel', '', 24209, 21144, 4320, 253, 893, 671, 51, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte seer', '', 36296, 15505, 4320, 253, 1223, 671, 55, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte seer', '', 36070, 15697, 4320, 253, 4065, 671, 55, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte seer', '', 40776, 25156, 4320, 253, 962, 671, 55, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'tomte seer', '', 41256, 25840, 4320, 253, 1135, 671, 55, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'young scimitar cat', '', 44687, 29227, 4320, 253, 4064, 695, 47, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'young scimitar cat', '', 44337, 30008, 4320, 253, 2105, 695, 47, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'young scimitar cat', '', 44477, 29517, 4320, 253, 1442, 695, 47, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'young scimitar cat', '', 32479, 46870, 3944, 253, 2544, 695, 47, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'young scimitar cat', '', 32082, 46978, 3944, 253, 987, 695, 47, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'young scimitar cat', '', 32039, 46921, 3944, 253, 864, 695, 47, 17, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'large red wolfhound', '', 41875, 31538, 4320, 253, 545, 56, 80, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'large red wolfhound', '', 42383, 31233, 4320, 253, 2978, 56, 80, 18, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'large red wolfhound', '', 41942, 31508, 4320, 253, 3066, 56, 80, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'large red wolfhound', '', 47632, 42521, 3944, 253, 3696, 56, 80, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'large red wolfhound', '', 48109, 42335, 3944, 253, 1954, 56, 80, 19, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'large red wolfhound', '', 48704, 42795, 3944, 253, 2155, 56, 80, 20, 'DOL.GS.GameNPC', 90, 350, 190, 300000, 0, 'gaheris-designed'),
(UUID(), 'Jarl Abermenai', 'Warlord', 36572, 31766, 4320, 253, 0, 153, 65, 19, 'DOL.GS.GameNPC', 95, 500, 190, 900000, 0, 'gaheris-designed');


-- ---------------------------------------------------------------------------
-- Wilton was never a configured battleground here
-- ---------------------------------------------------------------------------
-- The battleground table has 15-19, 20-24, 25-29, 30-34 and 45-49, and a hole
-- where 35-39 should be. Wilton was that band on live, so it fills its own gap.

DELETE FROM `battleground` WHERE `RegionID` = 240;
INSERT INTO `battleground` (`Battleground_ID`, `RegionID`, `MinLevel`, `MaxLevel`, `MaxRealmLevel`)
VALUES ('Wilton (Level 35-39)', 240, 35, 39, 30);

-- ---------------------------------------------------------------------------
-- Both on the Gate Warden, with a way home
-- ---------------------------------------------------------------------------

DELETE FROM `teleport` WHERE `Type` = 'gaheris' AND `RegionID` IN (240, 253);
DELETE FROM `mob` WHERE `PackageID` = 'gaheris-designed-warden';

INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Wilton', 0, 240, 554821, 584199, 6952, 0);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES (UUID(), 'Gate Warden', 'Gate Warden', 554941, 584319, 6952, 240, 0, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-designed-warden');
INSERT INTO `teleport` (`Teleport_ID`, `Type`, `TeleportID`, `Realm`, `RegionID`, `X`, `Y`, `Z`, `Heading`) VALUES (UUID(), 'gaheris', 'Abermenai', 0, 253, 18662, 18557, 4320, 0);
INSERT INTO `mob` (`Mob_ID`, `Name`, `Guild`, `X`, `Y`, `Z`, `Region`, `Heading`, `Model`, `Size`, `Level`, `ClassType`, `Flags`, `Realm`, `PackageID`) VALUES (UUID(), 'Gate Warden', 'Gate Warden', 18782, 18677, 4320, 253, 0, 63, 50, 70, 'DOL.GS.Scripts.GaherisTeleporter', 16, 0, 'gaheris-designed-warden');

-- ---------------------------------------------------------------------------
-- Check
-- ---------------------------------------------------------------------------
SELECT `Region`, COUNT(*) AS mobs, MIN(`Level`) AS lo, MAX(`Level`) AS hi
  FROM `mob` WHERE `PackageID` = 'gaheris-designed'
 GROUP BY `Region`;

SELECT `RegionID`, `MinLevel`, `MaxLevel` FROM `battleground` ORDER BY `MinLevel`;

